CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  created VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  account_status VARCHAR(255) NOT NULL DEFAULT 'normal'
)