CREATE TABLE IF NOT EXISTS codes (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(255) NOT NULL,
  item VARCHAR(255) NOT NULL,
  created VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_claimed BOOLEAN NOT NULL DEFAULT false
)